language: node_js
os: osx
node_js:
- 10.16.3
script:
- npm run build
- npm prune --production
- tar -cf build.tar .next node_modules package.json
cache:
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_0e6c454f6502_key -iv $encrypted_0e6c454f6502_iv
  -in deploy.tar.enc -out deploy.tar -d
- tar xvf deploy.tar
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master
